name: Java CI

on: push

jobs:
  run-test-and-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle and execute build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app