name: Java CI

on: push

jobs:
  run-test-and-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        #with:
          #arguments: build
          #build-root-directory: app
      - name: Execute Gradle build
        run: ls -la